/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc1e41fc912f6523e6c49fb74368a06c)
interface __BaseEnv_Env {
	SAASPASSE_WORKER_ORIGIN_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
